# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum_post',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='forum_postcomment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='topic_post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='topic_postcomment',
            options={'ordering': ['-date_created']},
        ),
    ]
