# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20170527_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='filetype',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='topic_post',
            name='filetype',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
